language: android
android:
   components:
   - platform-tools
   - android-23
   - tools
   - build-tools-23.0.2
   - extra

jdk: oraclejdk7

notifications:
  email: false

sudo: false

script:
  - ./gradlew assembleRelease check

after_success:
  - ./scripts/publish.sh

branches:
  only:
    - master
